global:
  scrape_interval: 5s  # Scrape metrics every 5 seconds

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["flask_app:5000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
